// Text for Preventive care module -- each topic has a "Text" (general discussion) and a "Rec" (individualized specific recommendation).


const pcIntroduction = "Welcome! By completing this form and answering a few questions, you’ve taken an important first step towards improving your health and protecting yourself from cardiovascular disease.  The information and recommendations presented below are all  evidence-based and validated.  Hopefully, they will provide useful guideposts on your journey to healthier living."
const pcRiskAssessmentText = "Assessing the risk of cardiovascular disease is the cornerstone of prevention.  The risk of a cardiac or vascular event can be estimated by evaluating a few simple factors.  The <b>'risk score'</b> value guides recommendations for optimizing lifestyle and treatment.  Those with low risk scores may not need to alter any lifestyle choices, while those with elevated risk scores have the most to gain by making a few changes.";
const pcRiskAssessmentRec = "<br>The intensity of recommended preventative measures and treatment are determined by the ten-year estimated risk of cardiovascular events.";
const pcNutritionText = "In general, diets that include high amounts of sugar, low-calorie sweeteners, refined grains, trans-fats, saturated fat, sodium, red meat, and processed red meats are associated with higher risks of heart and vascular disease.  Also, longstanding dietary patterns that focus on low intake of carbohydrates and a high intake of animal fat and protein as well as high carbohydrate diets are associated with higher rates of cardiac and noncardiac mortality.";
const pcNutritionRec = "Recommendation:  adults should consume a healthy plant-based or Mediterranean-like diet high in vegetables, lean vegetable or animal protein,fruits, nuts, whole grains and vegetable fiber. This type of diet has been shown to lower the risk of death compared to a standard diet.";
const pcPhysicalActivityText = "Extensive research shows that regular aerobic physical activity lowers the risk of heart and vascular disease.  Despite this, only about half the adults in the United States meet minimum exercise recommendations.";
const pcPhysicalActivityRec ="It is recommended that adults should engage in at least 150 minutes/week of moderate-intensity or 75 minutes/week of vigorous-intensity physical activity, including resistance exercise.";
const pcObesityText ="Excess weight contributes significantly to the risk of heart or vascular disease, such as heart attack, stroke, peripheral vascular disease, heart failure, and atrial fibrillation.  Obese and overweight adults benefit from lifestyle changes such as adhering to a low-calorie diet and high levels of physical activity. Even a relatively small degree of weight loss (more than 5% of initial weight) is associated with improved blood pressure, lower LDL-cholesterol,  lower triglycerides, improved glucose levels and protection against the development of diabetes.";
const pcObesityRec = "Recommendation:  Follow a calorie-restricted diet (decrease daily caloric intake by 500 kcal or follow a diet of 1200-1500 kcal/day) and engage in high levels of physical activity (200-300 minutes/week).";
const pcHypertensionText = "In the United States, high blood pressure is the number one contributor to death due to heart or vascular disease, more than any other modifiable risk factor. Almost half of the US population has stage I hypertension, and the incidence is higher in certain groups, including Blacks, Asians, and Hispanic Americans.  High blood pressure also increases dramatically with increasing age. Even modest increases in blood pressure have significant consequences.  An increase in systolic BP of 20 mm Hg or a diastolic BP of more than 10 mm Hg are each associated with a doubling in the risk of death from stroke, heart disease, or other vascular disease."; 
const pcHypertensionRec = "";
const pcDiabetesText = "Type 2 Diabetes, defined as a hemoglobin A1c (HbA1c) greater than 6.5%, is a metabolic disorder characterized by insulin resistance leading to elevated blood sugar. The development and progression of diabetes are significantly affected by diet, physical activity, and body weight. Diabetes is strongly related to the risk of developing cardiovascular disease, including heart attack, stroke and peripheral vascular disease.  But there is hope!  Lifestyle changes including healthy diet, exercise and weight control are effective in preventing the development of diabetes and controlling blood sugar.";
const pcDiabetesRec = "Nutritional counseling regarding a diet to promote weight loss and glycemic control.  Diets such as Mediterranean, DASH or vegan/vegetarian are beneficial.  Moderate to vigorous exercise of at least 150 minutes per week promotes a reduction in HgA1C of approximately 0.7 percentage points.  Any additional risk factors (smoking, hypertension, hyperlipidemia) should also be addressed.  For medication therapy, metformin is the standard for initial therapy, with a goal HgA1C of 6.6-7.0.  Use of metformin is associated with significant reduction in rates of heart attack and death.  Other agents, including the SGLT-1 inhibitors and the GLP-1R agonists, also reduce cardiovascular events in patients with known cardiovascular disease or at high risk for cardiovascular events.  These medications may also have a role in primary prevention of atherosclerotic vascular disease.";
const pcCholesterolText = "High cholesterol is closely associated with developing vascular disease, heart attack and stroke.  Prevention of cardiovascular disease requires assessing risk factors beginning in childhood and maintaining excellent control of cholesterol and other lipids throughout life.  A healthy lifestyle, diet, exercise, weight control and medications all have a role in reducing the risks of high cholesterol.";
const pcCholesterolRec = "";
const pcTobaccoUseText = "Tobacco use is the leading preventable cause of disease, disability, and death in the United States. Smoking increases the risk for cardiovascular disease and exposure to secondhand smoke is a significant cause of heart attack and stroke.  Almost one third of heart attack related deaths are attributable to smoking and exposure to secondhand smoke.  Other forms of inhaled nicotine, such as e-cigarettes and vaping, emit aerosol containing very fine particles, nicotine, and toxic gases that may increase the risk for heart and lung diseases, heart rhythm disorders and high blood pressure.";
const pcTobaccoUseRec = "Smokers are strongly advised to quit.  Tobacco use is addictive and quiting is difficult.   Sometimes, referral to specialists is helpful for behavioral modification, nicotine replacement, and/or drug treatments. Treatment may include varieties of nicotine replacement, the nicotine receptor blocker varenicline, and bupropion, an antidepressant.  Also, exposure to second-hand smoke is harmful and should be avoided.  ";
const pcAspirinText="Historically, low-dose aspirin has been widely administered for cardiovascular disease prevention.  The use of aspirin is well established for preventing future heart attacks following a first cardiac event, and should continue to be used for this purpose ('secondary prevention').  <br> However, recent studies have shown that in the modern era, with a few exceptions, aspirin should not be used routinely in individuals who have never had a heart attack.";
const pcAspirinRec = "The following recommendations are based on the best available recent  studies: <br> <ul> <li>Low-dose aspirin should not be administered on a routine basis for primary prevention of cardiovascular disease for adults >70 years.</li> <li>Low-dose aspirin should not be administered for primary prevention for adults at any age who are at increased bleeding risk (including a history of gastrointestinal bleeding, peptic ulcer disease, bleeding from other sites,  low platelet count, clotting disorder, chronic kidney disease, or concurrent use of nonsteroidal anti-inflammatory drugs, steroids, and anticoagulants (blood thinners).</li> <li>  Low-dose aspirin might be considered for primary prevention of cardiac or vascular disease in select higher risk adults aged 40-70 years who are not at increased bleeding risk.</li> </ul>";
const pcConclusion = "Congratulations! You have completed an important first step towards improving your health. The recommendations above may serve as a useful action list to guide you to better health.  Good luck on your journey to healthy living!"

